FROM python:3.8.13-slim-bullseye

WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# NOTE: LATER MODIFY THE DOCKER BUILD TO INSTALL A VERSION OF POSTGRES THAT'S COMPATIBLE WITH THE SERVER


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    netcat \
    wget \
    unzip \
    postgresql-client \
    dpkg && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade setuptools

ADD --chmod=655 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

ADD docker/requirements.development.txt /app/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip /root/.cargo/bin/uv pip install --system --no-cache -r requirements.txt

# Copy project files into container
ADD . /app

RUN sed -i "s/raise RuntimeError(\"populate() isn't reentrant\")/self.app_configs = {}/g" /usr/local/lib/python3.8/site-packages/django/apps/registry.py

# Copy the entrypoint script
COPY scripts/entrypoint.sh /app/scripts/entrypoint.sh
RUN chmod +x /app/scripts/entrypoint.sh

LABEL maintainer="info@fundusai.com"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="FundusAI API"
LABEL org.label-schema.description="FundusAI offers an artificial intelligence diagnostic device for Diabetic Retinopathy, allowing doctors to diagnose more patients in less time to prevent blindness in diabetic patients."
LABEL org.label-schema.url="https://fundusai.com"
LABEL org.label-schema.vcs-url="https://github.com/fundusai"
LABEL org.label-schema.vendor="FundusAI"

EXPOSE 8000

ENTRYPOINT ["/app/scripts/entrypoint.sh"]
