name: tests

on:
  - push
  - pull_request

jobs:
  test-python-38:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: mypassword
          POSTGRES_USERNAME: myuser
          POSTGRES_DB: database
          
        ports:
          - "5432:5432"
      redis:
        image: redis:latest
        ports:
          - "6379:6379"
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --no-cache pytest pytest-mock pytest-celery pytest-django
          uv pip install --no-cache -r requirements.txt
      - name: Copy .env.sample (if it exists) and add to secrets
        run: |
          if [ -f ".env.sample" ]; then
            cp .env.sample .env
            echo ".env" >> .gitignore
          fi
      - name: Run Tests
        run: |
          pytest tests  
        env:
          REDIS_URI: redis://redis:6379/0
          POSTGRES_URI: postgresql://myuser:mypassword@postgres:5432/database
          ENVIRONMENT: Dev
